<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "random_cache".
 *
 * @property integer $category
 * @property integer $index
 * @property integer $resource_id
 */
class RandomCache extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'random_cache';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category', 'index', 'resource_id'], 'required'],
            [['category', 'index', 'resource_id'], 'integer'],
        ];
    }

    public function getResource() {
        return $this->hasOne(Resource::className(), [ 'id' => 'resource_id']);
    }

    public function fields()
    {
        return ['resource']; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'category' => 'Category',
            'index' => 'Index',
            'resource_id' => 'Resource ID',
        ];
    }
}
